server:
  port: 8501

spring:

  application:
    name: worker

  # 数据源配置
  datasource:
    # 数据源选择
    type: com.alibaba.druid.pool.DruidDataSource
    # clickhouse配置
    click:
      driverClassName: com.clickhouse.jdbc.ClickHouseDriver
      url: jdbc:clickhouse://127.0.0.1:8123/alisa_log_product
      username: default
      password:
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000

  # redis配置
  redis:
    database: 3
    host: 127.0.0.1
    port: 6379
    password:
    jedis:
      pool:
        max-active: 10
        max-idle: 8
        min-idle: 0
        max-wait: 60s

# 心跳配置
heartbeat:
  # 该worker节点的外部访问IP
  address: 127.0.0.1
  # 该worker节点发送心跳的周期（单位：秒）
  cycle: 3
  # 连接的路由中心
  router:
    # 地址（多个路由中心地址用','隔开，例：http://127.0.0.1:8503,http://127.0.0.2:8503,http://127.0.0.3:8503）
    url: http://127.0.0.1:8503

# UDP配置
udp:
  port: 8500
  # 单个UDP数据包的大小限制（单位：字节）
  maxDataSize: 4096

# 缓冲队列配置
buffer:
  # 消费者配置
  consumer:
    # 消费线程数量
    number: 3
    # 每次最多消费多少条消息
    maxPoll: 1000
    # 每次最少消费多少条消息（建议设1000）
    minPoll: 1

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    # 使用jdbc的getGenerateKeys获取数据库自增主键值
    use-generated-keys: false
    # 使用列标签替换列别名 默认true
    use-column-label: true
    # 开启驼峰命名转换：Table{create_time} -> Entity{createTime}
    map-underscore-to-camel-case: true


