spring:
  application:
    name: worker
  # 数据源配置（默认使用mariadb，也可换成mysql，两者通用）
  datasource:
    url: jdbc:mariadb://127.0.0.1:3306/alisa_log_product?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password:
    driver-class-name: org.mariadb.jdbc.Driver

udp:
  port: 9000
  maxDataSize: 4096

# elasticsearch配置
elasticsearch:
  # 集群配置：http://127.0.0.1:9200,http://127.0.0.2:9200,http://127.0.0.3:9200 逗号间隔
  url: http://127.0.0.1:9200
  username: elastic
  password: 123456
  # 索引前缀
  indexPrefix: alisa-log-product-


