server:
  port: 9001
  servlet:
    # 路由前缀
    context-path: /alisa

spring:
  mvc:
    # 兼容Swagger3
    pathmatch:
      matching-strategy: ant_path_matcher

  application:
    name: worker
  # 数据源配置
  datasource:
    # 数据源选择
    type: com.alibaba.druid.pool.DruidDataSource
    # clickhouse配置
    click:
      driverClassName: ru.yandex.clickhouse.ClickHouseDriver
      url: jdbc:clickhouse://127.0.0.1:8123/alisa_log
      username: default
      password:
      initialSize: 10
      maxActive: 100
      minIdle: 10
      maxWait: 6000

# MyBatis-Plus配置
mybatis-plus:
  configuration:
    # 使用jdbc的getGenerateKeys获取数据库自增主键值
    use-generated-keys: true
    # 使用列标签替换列别名 默认true
    use-column-label: true
    # 开启驼峰命名转换：Table{create_time} -> Entity{createTime}
    map-underscore-to-camel-case: true


